<a href="https://colab.research.google.com/github/o-going/pdm01/blob/master/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [8]:
from numpy import asarray             # asarray => 입력된 데이터를 numpy.ndarray() 형식으로 만들어줌.
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [16]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):	
	print(data[row,:])	# 열로 출력

[1 2 3]
[4 5 6]


## Print columns

In [10]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col])	# 행으로 출력

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [24]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None)  # 전체 요소를 다 더해줌.(default: axis=None)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [26]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0) # 수직으로 요소를 더해줌
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [28]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1) # 수평으로 요소를 더해줌
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [도전하기]

- 3차원 배열을 리스트로부터 만드시오.

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''

In [29]:
data3d = [[1,2,3], [4,5,6], [7,8,9]]

In [30]:
data3d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
from numpy import asarray

data3d = asarray(data3d)

In [35]:
print(data3d)
data3d.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

### 3차원배열 : n * m * l, (n,m,l)

In [45]:
data3d = [[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]] # 대괄호 하나 더 만들어 줘야함.(3차원으로 만들기)
data3d = asarray(data3d)
print(data3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [37]:
data3d.ndim

3

In [38]:
data3d.sum(axis=0)  # axis=0 => 수직으로 각 자리에 있는 요소들을 더해줌 (column-wise)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [40]:
data3d.sum(axis=1)  # axis=1 => 수평으로 각 자리에 있는 요소들을 더해줌 (row-wise)

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

In [41]:
data3d.sum(axis=2)  # axis=2 => 3차원 :(3,2,3) 3개의 row에서 총 6번의 합이 계산이됨. 결국 shape(3,2)가 반환이 되는 것이고 남은 스칼라값을 계산.

array([[ 6, 15],
       [ 6, 15],
       [ 6, 15]])

* 튜플을 사용한 예제

In [ ]:
data3d.sum(axis=(0,1))  # 해당 튜플에 명시된 모든 axis에 대해서 연산 => axis=1 결과에따라 수직으로 더함

array([15, 21, 27])

In [42]:
data3d.sum(axis=(0,2))  # 해당 튜플에 명시된 모든 axis에 대해서 연산 => axis=2 결과에따라 수직으로 더함

array([18, 45])

In [43]:
data3d.sum(axis=(1,2))  # 해당 튜플에 명시된 모든 axis에 대해서 연산 => axis=2 결과에따라 수평으로 더함

array([21, 21, 21])

### [과제] 위의 3차원 배열에 대한 계산 결과를 간단히 주석으로 설명해보세요.